server:
  port: 4000
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true